version: "3.8"

services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: application