/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1/userguide/multi_project_builds.html
 */

rootProject.name = "leetcode"
rootProject.buildFileName = "${rootProject.name}.gradle.kts"

include("easy-difficulty")
include("medium-difficulty")
include("hard-difficulty")

pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}
//
//dependencyResolutionManagement {
//    repositories {
//        mavenLocal()
//        mavenCentral()
//    }
//}

/**
 * Name gradle build files after subprojects names
 */
rootProject.children.forEach {
    it.buildFileName = "${it.name}.gradle.kts"
}
